language: node_js
dist: trusty
sudo: required
node_js:
  - "12.13.1"
git:
  depth: 25
  quiet: true

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version version-number
  - export PATH="$HOME/.yarn/bin:$PATH"

branches:
  only:
  - master
  - development

stages:
  - name: "Test & Build"

jobs:
    include:
        - stage: "Test & Build"
          name: Build
          script: nx run lite-serve:build
        - stage: "Test & Build"
          name: Test
          script: nx run lite-serve-e2e:e2e

cache:
  directories:
  - node_modules
